parserOptions:
    ecmaVersion: 6
env:
    es6: true
    jasmine: true
    node: true
extends: eslint:recommended
rules:
    arrow-body-style:
        - error
        - always
    arrow-parens: error
    arrow-spacing: error
